version: "3"
services:
  app:
    build: .
    ports:
      - 8080:8080
    # depends_on:
    #   - db
    volumes:
      - .:/app

  # db:
  #   image: mysql:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=app_development
  #     - MYSQL_USER=app
  #     - MYSQL_PASSWORD=password
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db_data:/var/lib/mysql

volumes:
  db_data:
